__all__ = ["DEFAULT_SPACING", "TEXT_MODE", "IMAGE_MODE", "STRICT_RULE",
           "LAX_RULE", "DEFAULT_MAP_MODE", "DEFAULT_RULE", "BLOCK_SIZE",
           "RRADIUS", "PRADIUS"]

DEFAULT_SPACING = 25

TEXT_MODE = "text"
IMAGE_MODE = "image"

STRICT_RULE = "strict"
LAX_RULE = "lax"

DEFAULT_MAP_MODE = TEXT_MODE
DEFAULT_RULE = LAX_RULE

BLOCK_SIZE = 50
RRADIUS = 0.75
PRADIUS = 5
